services:
  django_app:
    build:
      context: ../LTPython/Webapp
      dockerfile: Dockerfile
    image: django_app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "/app/backend/wait-for-it.sh db:3306 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - "../LTPython/Webapp/.env"
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - django-app-nw

  db:
    image: mysql:8.0
    container_name: "db_cont"
    ports:
      - "3307:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=12345678
       - MYSQL_DATABASE=imag_app_db
       - MYSQL_USER=charos
       - MYSQL_PASSWORD=charos
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ucharos", "-pcharos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - django-app-nw

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - django-app-nw
    depends_on:
      - django_app

networks:
  django-app-nw:
    driver: bridge