# Generated by Django 5.1.7 on 2025-03-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_image_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chatbotmessage',
            name='chat_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbotmessages', to='ImageApp.chatturn'),
        ),
        migrations.AlterField(
            model_name='chatturn',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatturns', to='ImageApp.chat'),
        ),
        migrations.AlterField(
            model_name='image',
            name='chat_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ImageApp.chatturn'),
        ),
    ]
